---
version: "3"
services:

  ######### FRONTENDS ##########

  # Traefik Reverse Proxy
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/storage/docker/traefik/config:/etc/traefik
      - /mnt/storage/docker/shared:/shared

  # Organizer - Unified HTPC/Home Server Web Interface
  organizr:
    container_name: organizr
    restart: always
    image: lsiocommunity/organizr
    volumes:
      - /mnt/storage/docker/organizr/config:/config
      - /mnt/storage/docker/shared:/shared
    # ports:
    #   - "XXXX:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=organizr"
      - "traefik.frontend.rule=Host:organizr.${DOMAINNAME}"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /organizr"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"

  # phpMyAdmin - WebUI for MariaDB
  phpmyadmin:
    hostname: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mariadb:db
    # ports:
    #   - XXXX:80
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - traefik_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pma"
      - "traefik.frontend.rule=Host:pma.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"

  ######### DOCKER RELATED ##########

  # Watchtower - Automatic Update of Containers/Apps
  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

  ######### SMART HOME APPS ##########

  # Home Assistant - Smart Home Hub
  homeassistant:
    container_name: homeassistant
    restart: always
    image: homeassistant/home-assistant
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /mnt/storage/docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage/docker/shared:/shared
    # ports:
    #   - "XXXX:8123"
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=homeassistant"
      - "traefik.frontend.rule=Host:hass.${DOMAINNAME}"
      - "traefik.port=8123"
      - "traefik.docker.network=traefik_proxy"

  ######### DOWNLOADERS ##########

  # transmission – Bittorrent Downloader (Alternative)
  transmission:
    image: "linuxserver/transmission"
    container_name: "transmission"
    volumes:
      - /mnt/storage/docker/transmission/config:/config
      - /mnt/storage/Downloads/complete:/downloads
      - /mnt/storage/Downloads/watch:/watch
      - /mnt/storage/docker/shared:/shared
    ports:
      - "9090:9090"
      - "51413:51413"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=transmission"
      - "traefik.frontend.rule=Host:transmission.${DOMAINNAME}"
      - "traefik.port=9090"
      - "traefik.docker.network=traefik_proxy"


  # qBittorrent without VPN – Bittorrent Downloader (Alternative)
  qbittorrent:
    image: "linuxserver/qbittorrent"
    container_name: "qbittorrent"
    volumes:
      - /mnt/storage/docker/qbittorrent/config:/config
      - /mnt/storage/Downloads/completed:/downloads
      - /mnt/storage/docker/shared:/shared
    ports:
      # - "XXXX:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=qbittorrent"
      - "traefik.frontend.rule=Host:qbit.${DOMAINNAME}"
      - "traefik.port=XXXX"
      - "traefik.docker.network=traefik_proxy"

  # SABnzbd – Usenet (NZB) Downloader
  sabnzbd:
    image: "linuxserver/sabnzbd"
    container_name: "sabnzbd"
    volumes:
      - /mnt/storage/docker/sabnzbd/config:/config
      - /mnt/storage/Downloads/complete:/downloads
      - /mnt/storage/Downloads/incomplete:/incomplete-downloads
      - /mnt/storage/docker/shared:/shared
    # ports:
    #   - "XXXX:8080"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sabnzbd"
      - "traefik.frontend.rule=Host:sabnzbd.${DOMAINNAME}"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefix: /sabnzbd"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"

  ######### PERSONAL VIDEO RECORDERS ##########

  # Radarr – Movie Download and Management
  couchpotato:
    image: "linuxserver/couchpotato"
    container_name: "couchpotato"
    volumes:
      - /mnt/storage/docker/couchpotato/config:/config
      - /mnt/storage/Downloads/complete:/downloads
      - /mnt/storage/media/Movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - /mnt/storage/docker/shared:/shared
    # ports:
    #   - "5050:5050"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=couchpotato"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefix: /couchpotato"
      - "traefik.frontend.rule=Host:couchpotato.${DOMAINNAME}"
      - "traefik.port=5050"
      - "traefik.docker.network=traefik_proxy"

  # Radarr – Movie Download and Management
  radarr:
    image: "linuxserver/radarr"
    container_name: "radarr"
    volumes:
      - /mnt/storage/docker/radarr/config:/config
      - /mnt/storage/Downloads/complete:/downloads
      - /mnt/storage/media/Movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - /mnt/storage/docker/shared:/shared
    # ports:
    #   - "XXXX:7878"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=radarr"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefix: /radarr"
      - "traefik.frontend.rule=Host:radarr.${DOMAINNAME}"
      - "traefik.port=7878"
      - "traefik.docker.network=traefik_proxy"

  # Sonarr – TV Show Download and Management
  sonarr:
    image: "linuxserver/sonarr"
    container_name: "sonarr"
    volumes:
      - /mnt/storage/docker/sonarr/config:/config
      - /mnt/storage/Downloads/complete:/downloads
      - /mnt/storage/media/TV:/tv
      - "/etc/localtime:/etc/localtime:ro"
      - /mnt/docker/shared:/shared
    # ports:
    #   - "XXXX:8989"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefix: /sonarr"
      - "traefik.frontend.rule=Host:sonarr.${DOMAINNAME}"
      - "traefik.port=8989"
      - "traefik.docker.network=traefik_proxy"

  # LIDARR - Music Download and Management
  lidarr:
    image: "linuxserver/lidarr"
    hostname: lidarr
    container_name: "lidarr"
    volumes:
      - /mnt/storage/docker/lidarr/config:/config
      - /mnt/storage/Downloads:/downloads
      - /mnt/storage/media/Music:/music
      - "/etc/localtime:/etc/localtime:ro"
      - /mnt/storage/docker/shared:/shared
    # ports:
    #   - "XXXX:8686"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=lidarr"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefix: /lidarr"
      - "traefik.frontend.rule=Host:lidarr.${DOMAINNAME}"
      - "traefik.port=8686"
      - "traefik.docker.network=traefik_proxy"

  ######### MEDIA SERVER APPS ##########

  # Plex Media Server
  plexms:
    container_name: plexms
    restart: always
    image: plexinc/pms-docker
    volumes:
      - /mnt/storage/docker/plex/config:/config
      - /mnt/storage/docker/plex/transcode:/transcode
      - /mnt/storage/media:/media
      - /mnt/storage/docker/shared:/shared
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=${TZ}
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM="claim-YYYYYYYYY"
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP="http://SERVER-IP:32400/"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plexms"
      - "traefik.frontend.rule=Host:plex.${DOMAINNAME}"
      - "traefik.port=32400"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_proxy"

  # Tautulli (aka PlexPy) – Monitoring Plex Usage
  tautulli:
    container_name: tautulli
    restart: always
    image: linuxserver/tautulli
    volumes:
      - /mnt/storage/docker/tautulli/config:/config
      - /mnt/storage/docker/tautulli/logs:/logs:ro
      - /mnt/storage/docker/shared:/shared
    # ports:
    #   - "XXXX:8181"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=tautulli"
      - "traefik.frontend.rule=Host:tautulli.${DOMAINNAME}"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefix: /tautulli"
      - "traefik.port=8181"
      - "traefik.docker.network=traefik_proxy"

  # Ombi – Accept Requests for your Media Server
  ombi:
    container_name: ombi
    restart: always
    image: linuxserver/ombi
    volumes:
      - /mnt/storage/docker/ombi/config:/config
      - /mnt/storage/docker/shared:/shared
    # ports:
    #   - "XXXX:3579"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ombi"
      - "traefik.frontend.rule=Host:ombi.${DOMAINNAME}"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefix: /ombi"
      - "traefik.port=3579"
      - "traefik.docker.network=traefik_proxy"

  ######### SEARCHERS ##########

  # NZBHydra – NZB Meta Search
  hydra:
    image: "linuxserver/hydra"
    container_name: "hydra"
    volumes:
      - /mnt/storage/docker/hydra/config:/config
      - /mnt/storage/Downloads:/downloads
      - /mnt/storage/docker/shared:/shared
    # ports:
    #   - "XXXX:5075"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=hydra"
      - "traefik.frontend.rule=Host:hydra.${DOMAINNAME}"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefix: /hydra"
      - "traefik.port=5075"
      - "traefik.docker.network=traefik_proxy"

  # Jackett – Torrent Proxy
  jackett:
    image: "linuxserver/jackett"
    container_name: "jackett"
    volumes:
      - /mnt/storage/docker/jackett/config:/config
      - /mnt/storage/Downloads/complete:/downloads
      - "/etc/localtime:/etc/localtime:ro"
      - /mnt/storage/docker/shared:/shared
    # ports:
    #   - "XXXX:9117"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jackett"
      - "traefik.frontend.rule=Host:jackett.${DOMAINNAME}"
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefix: /jackett"
      - "traefik.port=9117"
      - "traefik.docker.network=traefik_proxy"

  ######### UTILITIES ##########

  # MariaDB – Database Server for your Apps
  mariadb:
    image: "linuxserver/mariadb"
    container_name: "mariadb"
    hostname: mariadb
    volumes:
      - /mnt/storage/docker/mariadb/config:/config
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  # NextCloud – Your Own Cloud Storage
  nextcloud:
    container_name: nextcloud
    restart: always
    image: linuxserver/nextcloud
    volumes:
      - /mnt/storage/docker/nextcloud/config:/config
      - /mnt/storage/docker/nextcloud/shared_data:/data
      - /mnt/storage/docker/shared:/shared
    # ports:
    #   - "XXXX:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:nextcloud.${DOMAINNAME}"
      - "traefik.port=443"
      - "traefik.protocol=https"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
